### PR TITLE
Yusuf us4 refill

### PR DESCRIPTION
**Pull request by erguculu**
Added css and html in page refill stations

### CODE REVIEW

**Review by FranciscoKevin — DISMISSED** [review]
Ok pour moi.

**Review by RomainClair — CHANGES_REQUESTED** [review]
The assets/styles/refillStations.scss is invalid. Please use validators before PR
The apache-pack (and the .htaccess) is probably useless and can cause problem for CD

**Review by FranciscoKevin — APPROVED** [review]
Ok pour les changements

**Review by FranciscoKevin — APPROVED** [review]
Ok pour moi

**Review by RomainClair — APPROVED** [review]

**Pull request merged**
